# Generated by Django 5.2.7 on 2025-11-04 18:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Adresses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pays', models.CharField(max_length=50, verbose_name='Pays')),
                ('ville', models.CharField(max_length=50, verbose_name='Ville')),
                ('rue', models.CharField(max_length=100, verbose_name='Rue')),
                ('numero', models.CharField(max_length=10, verbose_name='Numéro')),
                ('boite', models.CharField(max_length=20, verbose_name='Boîte Postale')),
                ('code_postal', models.CharField(max_length=20, verbose_name='Code Postal')),
                ('province', models.CharField(max_length=50, verbose_name='Province')),
            ],
            options={
                'verbose_name': 'Adresse',
                'verbose_name_plural': 'Adresses',
                'ordering': ('pays', 'ville', 'province'),
            },
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, unique=True, verbose_name='Nom')),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories_images/', verbose_name='Illustration_categorie')),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'ordering': ('nom',),
            },
        ),
        migrations.CreateModel(
            name='Promotions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, verbose_name='Nom')),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Promotion',
                'verbose_name_plural': 'Promotions',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='Unites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20, unique=True, verbose_name='Nom')),
            ],
            options={
                'verbose_name': 'Unité',
                'verbose_name_plural': 'Unités',
                'ordering': ('nom',),
            },
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_telephone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('est_admin', models.BooleanField(default=False, verbose_name='Administrateur')),
                ('adresse', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='clic_n_local_app.adresses', verbose_name='Adresse')),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ('utilisateur__last_name', 'utilisateur__first_name'),
            },
        ),
        migrations.CreateModel(
            name='Commandes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_commande', models.DateTimeField(auto_now_add=True, verbose_name='Date de la commande')),
                ('statut', models.CharField(choices=[('panier', 'Panier'), ('commande', 'Commandé')], default='panier', max_length=20, verbose_name='Statut')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clic_n_local_app.clients', verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Commande',
                'verbose_name_plural': 'Commandes',
                'ordering': ('-date_commande',),
            },
        ),
        migrations.CreateModel(
            name='Produits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_produit', models.CharField(max_length=50, verbose_name='Nom')),
                ('description', models.CharField(max_length=200, verbose_name='Description')),
                ('quantite', models.IntegerField(default=0, verbose_name='Quantité')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clic_n_local_app.categories', verbose_name='Catégorie')),
                ('unite_de_vente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clic_n_local_app.unites', verbose_name='Unité de vente')),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
                'ordering': ('nom_produit', 'prix'),
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255, unique=True, verbose_name='URL')),
                ('ordre', models.IntegerField(default=1, verbose_name='Ordre')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clic_n_local_app.produits', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='PromotionsProduits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('POURCENTAGE', 'Pourcentage'), ('MONTANT', 'Montant fixe')], max_length=20, verbose_name='Type de promotion')),
                ('valeur_promo', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valeur de la promotion')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clic_n_local_app.produits')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clic_n_local_app.promotions')),
            ],
            options={
                'verbose_name': 'Promotion sur produit',
                'verbose_name_plural': 'Promotions sur produits',
                'unique_together': {('produit', 'promotion')},
            },
        ),
    ]
