# Generated by Django 5.2.7 on 2025-11-04 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clic_n_local_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='categories_images/', verbose_name='Image pour la categorie'),
        ),
    ]
