# Generated by Django 5.2.7 on 2025-11-04 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clic_n_local_app', '0002_alter_categories_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='images',
            options={'ordering': ('ordre',), 'verbose_name': 'Image', 'verbose_name_plural': 'Images'},
        ),
        migrations.RemoveField(
            model_name='images',
            name='url',
        ),
        migrations.AddField(
            model_name='images',
            name='image',
            field=models.ImageField(null=True, upload_to='produits_images/', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='images',
            name='principale',
            field=models.BooleanField(default=False, verbose_name='Image principale'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='categories_images/', verbose_name='Illustration'),
        ),
        migrations.AlterField(
            model_name='images',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='clic_n_local_app.produits', verbose_name='Produit'),
        ),
    ]
