# Generated by Django 5.2.7 on 2025-11-21 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clic_n_local_app', '0003_alter_images_options_remove_images_url_images_image_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='promotionsproduits',
            unique_together=set(),
        ),
    ]
