# Generated by Django 5.2.7 on 2025-11-25 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clic_n_local_app', '0004_alter_promotionsproduits_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='categories_images/', verbose_name='Illustration'),
        ),
    ]
