# Generated by Django 5.2.7 on 2025-11-28 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clic_n_local_app', '0005_alter_categories_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommandesProduits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField(default=1, verbose_name='Quantité')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix au moment de la commande')),
                ('rabais', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Rabais appliqué')),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clic_n_local_app.commandes', verbose_name='Commande')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clic_n_local_app.produits', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Produit dans la commande',
                'verbose_name_plural': 'Produits dans les commandes',
            },
        ),
    ]
