# Generated by Django 5.2.7 on 2025-12-02 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clic_n_local_app', '0006_commandesproduits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commandesproduits',
            name='rabais',
        ),
        migrations.AddField(
            model_name='commandesproduits',
            name='prix_promo',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Prix avec promotion appliquée'),
        ),
        migrations.AlterField(
            model_name='adresses',
            name='boite',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Boîte Postale'),
        ),
        migrations.AlterField(
            model_name='commandesproduits',
            name='commande',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='clic_n_local_app.commandes', verbose_name='Commande'),
        ),
    ]
